Resources:
  CodeBuildRole:
    Type: "AWS::IAM::Role"
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "codebuild.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Policies:
        -
          PolicyName: "CodeBuildRolePolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action: 
                  - "ec2:*"
                  - "cloudwatch:*"
                  - "s3:*"
                  - "logs:*"
                  - "ecr:*"
                  - "cloudfront:*"
                  - "cloudformation:*"
                  - "iam:*"
                  - "lambda:*"
                  - "events:*"
                  - "apigateway:*"
                  - "es:*"
                  - "sqs:*"
                  - "secretsmanager:*"
                Resource: "*"
  CodePipelineRole:
    Type: "AWS::IAM::Role"
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "codepipeline.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Policies:
        -
          PolicyName: "CodePipelineRolePolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action: 
                  - "s3:*"
                  - "cloudformation:*"
                  - "codebuild:*"
                Resource: "*"
Outputs:
  CodeBuildRole:
    Value: !GetAtt 'CodeBuildRole.Arn'
    Description: CodeBuildRole arn
    Export: 
      Name: !Sub "${AWS::StackName}-CodeBuildRole"
  CodePipelineRole:
    Value: !GetAtt 'CodePipelineRole.Arn'
    Description: CodePipelineRole arn
    Export: 
      Name: !Sub "${AWS::StackName}-CodePipelineRole"